#ifndef GRAPHICSITEMTYPE_H
#define GRAPHICSITEMTYPE_H

//define utitlites types for all utilites 1-1999
#define GRAPHICSITEM_TYPE_RECT_PICKER    1
#define GRAPHICSITEM_TYPE_GROUP_PICKER   2
#define GRAPHICSITEM_TYPE_PICKER_OUTLINE 3
#define GRAPHICSITEM_TYPE_PICKER_ARCHOR  4
#define GRAPHICSITEM_TYPE_WORKSHEET      5
#define GRAPHICSITEM_TYPE_LOADERPIXMAP   6
#define GRAPHICSITEM_TYPE_LOADER         7


//define object types for baseelement 20000 - ...
#define GRAPHICSITEM_TYPE_BASEELEMENT    20000
#define GRAPHICSITEM_TYPE_FOLDER         20001
#define GRAPHICSITEM_TYPE_GROUP          20002
#define GRAPHICSITEM_TYPE_PIXMAP         20003
#define GRAPHICSITEM_TYPE_SVG            20005

#define GRAPHICSITEM_TYPE_ARC            20020
#define GRAPHICSITEM_TYPE_CIRCLE         20021
#define GRAPHICSITEM_TYPE_ELLIPSE        20022
#define GRAPHICSITEM_TYPE_LINE           20023
#define GRAPHICSITEM_TYPE_BEZIER         20024
#define GRAPHICSITEM_TYPE_PATH           20025
#define GRAPHICSITEM_TYPE_POLYGON        20026
#define GRAPHICSITEM_TYPE_RECT           20027
#define GRAPHICSITEM_TYPE_TEXT           20028
#define GRAPHICSITEM_TYPE_BASEELEMENT_END 20099 //SVG USE



#define GRAPHICSITEM_TYPE_GALLERYITEM        20100
#define GRAPHICSITEM_TYPE_THUMB              20101
#define GRAPHICSITEM_TYPE_GALLERYITEM_END    20199

#endif // GRAPHICSITEMTYPE_H
